// Generated by CoffeeScript 1.10.0
(function() {
  this.Rps = angular.module("Rps", []);

  this.Rps.controller('MainCtrl', [
    '$scope', 'GameService', function($scope, GameService) {
      var drawImages;
      $scope.selectorValue;
      $scope.result;
      $scope.decide = function() {
        $scope.playerDecision = $scope.selectorValue;
        $scope.computerDecision = GameService.getComputerMove();
        $scope.result = GameService.decide($scope.selectorValue);
        $scope.playerDecisionImage = drawImages($scope.computerDecision);
        return $scope.computerDecisionImage = drawImages($scope.playerDecision);
      };
      return drawImages = function(decision) {
        if (decision === "Rock") {
          return 'https://upload.wikimedia.org/wikipedia/commons/3/35/Stonehenge_on_27.01.08.jpg';
        } else if (decision === "Scissors") {
          return 'http://au.fiskars.com/var/fiskars_emea/storage/images/frontpage2/crafting-sewing/products/scissors/classic-scissors/2679613-4-eng-EU/Classic-Scissors.png';
        } else {
          return 'http://www.officexpress.co.uk/wp-content/uploads/2014/03/paper.jpg';
        }
      };
    }
  ]);

}).call(this);
