// Generated by CoffeeScript 1.10.0
(function() {
  this.Rps.factory('GameService', function() {
    var getWinner, self;
    self = {};
    self.getComputerMove = function() {
      var randomNumber;
      randomNumber = Math.random();
      if (randomNumber < 0.33) {
        return self.computerMove = "Rock";
      } else if (randomNumber < 0.66) {
        return self.computerMove = "Paper";
      } else {
        return self.computerMove = "Scissors";
      }
    };
    getWinner = function(playerMove) {
      var winner, winningMap;
      winningMap = {
        Rock: "Paper",
        Paper: "Scissors",
        Scissors: "Rock"
      };
      if (playerMove === winningMap[self.computerMove]) {
        winner = "Player";
      } else if (playerMove === self.computerMove) {
        winner = "tie";
      } else {
        winner = "Computer";
      }
      return winner;
    };
    self.decide = function(decision) {
      return getWinner(decision);
    };
    return self;
  });

}).call(this);
